import React from 'react';
import { PageWrapper } from '../components/layout/PageWrapper';
import { Settings, Save, Bell, Smartphone, User, Shield } from 'lucide-react';

export default function GlobalSettings() {
  return (
    <PageWrapper title="Global Settings" description="Manage global application preferences and alert routing.">
      <div className="max-w-3xl space-y-6">
        <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-6">
          <h3 className="text-lg font-medium text-white mb-4 flex items-center gap-2">
            <Smartphone className="w-5 h-5 text-primary" />
            Delivery Endpoints
          </h3>
          <p className="text-sm text-neutral-400 mb-6">
            Register external accounts (WhatsApp numbers, Facebook PSIDs) where you or your team can receive alerts.
          </p>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-1">Developer WhatsApp Number</label>
              <input type="text" placeholder="e.g. +20 100 123 4567" defaultValue="+20 100 000 0001" className="w-full bg-[#0a0a0a] border border-neutral-700 rounded-lg px-4 py-2 text-sm text-white focus:outline-none focus:border-primary" />
            </div>
            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-1">Sales Team WhatsApp Number / Group ID</label>
              <input type="text" placeholder="e.g. +20 111 987 6543" className="w-full bg-[#0a0a0a] border border-neutral-700 rounded-lg px-4 py-2 text-sm text-white focus:outline-none focus:border-primary" />
            </div>
            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-1">Support Team Facebook Account (PSID)</label>
              <input type="text" placeholder="e.g. 1092837465" className="w-full bg-[#0a0a0a] border border-neutral-700 rounded-lg px-4 py-2 text-sm text-white focus:outline-none focus:border-primary" />
            </div>
          </div>
        </div>

        <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-6">
          <h3 className="text-lg font-medium text-white mb-4 flex items-center gap-2">
            <Bell className="w-5 h-5 text-primary" />
            Alert Routing Preferences
          </h3>
          <p className="text-sm text-neutral-400 mb-6">
            Configure where and how you receive alerts generated by the system or AI.
          </p>
          
          <div className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 border-b border-neutral-800 pb-4">
              <div>
                <label className="block text-sm font-medium text-neutral-300 mb-1">New Ticket Alerts</label>
                <div className="text-xs text-neutral-500">When a high-priority ticket is created.</div>
              </div>
              <div className="flex flex-col gap-2">
                <label className="flex items-center gap-2"><input type="checkbox" className="accent-primary" defaultChecked /> <span className="text-sm text-neutral-300">Admin Panel (In-App)</span></label>
                <label className="flex items-center gap-2"><input type="checkbox" className="accent-primary" defaultChecked /> <span className="text-sm text-neutral-300">My Developer WhatsApp</span></label>
                <label className="flex items-center gap-2"><input type="checkbox" className="accent-primary" /> <span className="text-sm text-neutral-300">Sales Team WhatsApp Group</span></label>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 border-b border-neutral-800 pb-4">
              <div>
                <label className="block text-sm font-medium text-neutral-300 mb-1">AI Intervention Required</label>
                <div className="text-xs text-neutral-500">When AI cannot confidently answer a client's message.</div>
              </div>
              <div className="flex flex-col gap-2">
                <label className="flex items-center gap-2"><input type="checkbox" className="accent-primary" defaultChecked /> <span className="text-sm text-neutral-300">Admin Panel (In-App)</span></label>
                <label className="flex items-center gap-2"><input type="checkbox" className="accent-primary" /> <span className="text-sm text-neutral-300">My Developer WhatsApp</span></label>
                <label className="flex items-center gap-2"><input type="checkbox" className="accent-primary" defaultChecked /> <span className="text-sm text-neutral-300">Support Team Facebook Messenger</span></label>
              </div>
            </div>
          </div>
          
          <div className="mt-6 flex justify-end">
            <button className="bg-primary hover:bg-primary-hover text-white px-4 py-2 rounded text-sm font-medium flex items-center gap-2 transition-colors">
              <Save className="w-4 h-4" />
              Save Settings
            </button>
          </div>
        </div>
      </div>
    </PageWrapper>
  );
}
